# Generated by Django 4.2.6 on 2023-10-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration', models.CharField(choices=[('1 year', '1 year'), ('6 months', '6 months'), ('3 months', '3 months')], default='3 months', max_length=100)),
                ('fees', models.IntegerField()),
                ('mode_type', models.CharField(choices=[('online', 'Online'), ('blended', 'Blended'), ('offline', 'Offline')], default='offline', max_length=100)),
            ],
        ),
    ]
