# Generated by Django 4.2.6 on 2023-10-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture',
            field=models.FileField(upload_to='lectures'),
        ),
    ]
