# Generated by Django 4.2.6 on 2023-10-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lecture_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture',
            field=models.FileField(upload_to='lectures/'),
        ),
    ]
